import type { Question } from '@/domain/types'

type Q = Omit<Question, 'active'>
const ALL: Q['groups'] = [1, 2, 3]

export const QUESTION_BANK: Q[] = [
  // D1 · Estados financieros
  { id: 'd1-esf', dimension: 'D1', order: 10, weight: 3, requiresFlag: null, groups: ALL, niifSection: 'Sección 4', lesson: 'presentacion',
    text: '¿Prepara el estado de situación financiera (balance general) al cierre de cada año?',
    help: 'Muestra lo que la empresa tiene, lo que debe y su patrimonio en una fecha.',
    gap: 'No prepara el estado de situación financiera',
    fix: 'Prepare el estado de situación financiera al cierre, separando partidas corrientes y no corrientes.' },
  { id: 'd1-eri', dimension: 'D1', order: 20, weight: 3, requiresFlag: null, groups: ALL, niifSection: 'Sección 5', lesson: 'presentacion',
    text: '¿Prepara el estado de resultados del año?',
    help: 'Muestra ingresos, costos, gastos y la utilidad o pérdida del período.',
    gap: 'No prepara el estado de resultados',
    fix: 'Prepare el estado de resultados del período con ingresos, costos y gastos.' },
  { id: 'd1-flujo', dimension: 'D1', order: 30, weight: 2, requiresFlag: null, groups: [1, 2], niifSection: 'Sección 7', lesson: 'flujo-efectivo',
    text: '¿Prepara el estado de flujos de efectivo?',
    help: 'Explica de dónde vino y en qué se usó el efectivo: operación, inversión y financiación.',
    gap: 'No prepara el estado de flujos de efectivo',
    fix: 'Prepare el estado de flujos de efectivo por el método indirecto, a partir del balance y el estado de resultados.' },
  { id: 'd1-patrimonio', dimension: 'D1', order: 40, weight: 2, requiresFlag: null, groups: [1, 2], niifSection: 'Sección 6', lesson: 'presentacion',
    text: '¿Prepara el estado de cambios en el patrimonio?',
    help: 'Muestra cómo cambiaron el capital, las reservas y las utilidades acumuladas.',
    gap: 'No prepara el estado de cambios en el patrimonio',
    fix: 'Prepare el estado de cambios en el patrimonio con los movimientos de cada componente.' },
  { id: 'd1-notas', dimension: 'D1', order: 50, weight: 3, requiresFlag: null, groups: ALL, niifSection: 'Sección 8', lesson: 'notas',
    text: '¿Sus estados financieros incluyen notas explicativas?',
    help: 'Las notas explican las políticas usadas y el detalle de las cifras.',
    gap: 'Los estados financieros no tienen notas',
    fix: 'Redacte notas con las políticas contables, los juicios y el detalle de las partidas importantes.' },
  { id: 'd1-comparativos', dimension: 'D1', order: 60, weight: 2, requiresFlag: null, groups: ALL, niifSection: 'Sección 3', lesson: 'presentacion',
    text: '¿Presenta las cifras del año actual junto a las del año anterior?',
    help: 'La norma exige información comparativa de al menos un período anterior.',
    gap: 'No presenta información comparativa',
    fix: 'Presente cada estado con la columna del año anterior.' },
  { id: 'd1-aprobacion', dimension: 'D1', order: 70, weight: 1, requiresFlag: null, groups: ALL, niifSection: 'Sección 3', lesson: 'presentacion',
    text: '¿La asamblea o junta de socios aprueba los estados financieros?',
    help: 'La aprobación formal da validez a las cifras frente a terceros.',
    gap: 'Los estados financieros no se aprueban formalmente',
    fix: 'Presente los estados financieros para aprobación del máximo órgano social cada año.' },

  // D2 · Políticas contables
  { id: 'd2-manual', dimension: 'D2', order: 110, weight: 3, requiresFlag: null, groups: ALL, niifSection: 'Sección 10', lesson: 'politicas',
    text: '¿Tiene un manual de políticas contables por escrito?',
    help: 'Define cómo la empresa reconoce y mide cada partida bajo NIIF.',
    gap: 'No tiene manual de políticas contables',
    fix: 'Redacte un manual de políticas contables basado en las secciones que aplican a su empresa.' },
  { id: 'd2-aprobado', dimension: 'D2', order: 120, weight: 1, requiresFlag: null, groups: ALL, niifSection: 'Sección 10', lesson: 'politicas',
    text: '¿La gerencia o la junta aprobó ese manual?',
    help: 'Si no tiene manual, responda No.',
    gap: 'El manual de políticas no está aprobado',
    fix: 'Someta el manual a aprobación de la gerencia o la junta.' },
  { id: 'd2-aplicado', dimension: 'D2', order: 130, weight: 2, requiresFlag: null, groups: ALL, niifSection: 'Sección 10', lesson: 'politicas',
    text: '¿El equipo contable aplica las políticas en el día a día?',
    help: 'Un manual que no se usa no cambia las cifras.',
    gap: 'Las políticas no se aplican en la práctica',
    fix: 'Capacite al equipo y revise en cada cierre que los registros sigan las políticas.' },
  { id: 'd2-actualizado', dimension: 'D2', order: 140, weight: 1, requiresFlag: null, groups: ALL, niifSection: 'Sección 10', lesson: 'politicas',
    text: '¿Actualiza las políticas cuando cambian las normas o el negocio?',
    help: 'Por ejemplo, al empezar a manejar inventarios o a tomar un leasing.',
    gap: 'Las políticas no se actualizan',
    fix: 'Revise el manual al menos una vez al año.' },
  { id: 'd2-errores', dimension: 'D2', order: 150, weight: 2, requiresFlag: null, groups: ALL, niifSection: 'Sección 10', lesson: 'politicas',
    text: '¿Corrige los errores de años anteriores ajustando las cifras comparativas?',
    help: 'Los errores importantes de años anteriores se corrigen hacia atrás, no contra la utilidad del año.',
    gap: 'Los errores de períodos anteriores no se corrigen de forma retroactiva',
    fix: 'Corrija los errores materiales reexpresando la información comparativa y revélelo en notas.' },

  // D3 · Reconocimiento y medición
  { id: 'd3-inv-medicion', dimension: 'D3', order: 210, weight: 3, requiresFlag: 'inventarios', groups: ALL, niifSection: 'Sección 13', lesson: 'inventarios',
    text: '¿Mide sus inventarios al menor valor entre su costo y su precio de venta menos los costos para venderlos?',
    help: 'Si un producto se venderá por menos de lo que costó, hay que reducir su valor en libros.',
    gap: 'Los inventarios no se miden al menor entre costo y precio de venta menos costos de venta',
    fix: 'Compare al cierre el costo de cada línea con su precio de venta estimado menos costos de venta y ajuste la diferencia.' },
  { id: 'd3-inv-conteo', dimension: 'D3', order: 220, weight: 2, requiresFlag: 'inventarios', groups: ALL, niifSection: 'Sección 13', lesson: 'inventarios',
    text: '¿Hace conteos físicos de inventario y ajusta las diferencias?',
    help: 'Confirma que lo registrado existe de verdad.',
    gap: 'No se hacen conteos físicos de inventario',
    fix: 'Haga al menos un conteo físico al año y registre los ajustes.' },
  { id: 'd3-ppe-vida-util', dimension: 'D3', order: 230, weight: 3, requiresFlag: 'activosFijos', groups: ALL, niifSection: 'Sección 17', lesson: 'propiedad-planta-equipo',
    text: '¿Deprecia sus activos fijos según su vida útil real y no solo según las tasas fiscales?',
    help: 'La vida útil contable refleja cuánto tiempo usará realmente el activo.',
    gap: 'La depreciación sigue tasas fiscales y no la vida útil real',
    fix: 'Estime la vida útil y el valor residual de cada grupo de activos y deprécielos con esas estimaciones.' },
  { id: 'd3-ppe-deterioro', dimension: 'D3', order: 240, weight: 2, requiresFlag: 'activosFijos', groups: ALL, niifSection: 'Sección 27', lesson: 'deterioro',
    text: '¿Revisa al cierre si algún activo perdió valor por daño, obsolescencia o poco uso?',
    help: 'Esa pérdida se llama deterioro de valor.',
    gap: 'No se evalúa el deterioro de los activos',
    fix: 'Al cierre, revise indicios de deterioro y, si existen, calcule el importe recuperable del activo.' },
  { id: 'd3-arrendamientos', dimension: 'D3', order: 250, weight: 2, requiresFlag: 'arrendamientos', groups: ALL, niifSection: 'Sección 20', lesson: 'arrendamientos',
    text: '¿Clasifica sus arriendos y leasings como financieros u operativos y los registra según esa clasificación?',
    help: 'Un leasing financiero se registra como activo y deuda, no solo como gasto mensual.',
    gap: 'Los arrendamientos no se clasifican ni registran según la norma',
    fix: 'Analice cada contrato: si transfiere los riesgos y ventajas del activo, regístrelo como activo y pasivo.' },
  { id: 'd3-cartera', dimension: 'D3', order: 260, weight: 3, requiresFlag: 'financiamiento', groups: ALL, niifSection: 'Sección 11', lesson: 'instrumentos-financieros',
    text: '¿Evalúa al cierre si hay cartera de difícil cobro y registra su deterioro?',
    help: 'Cuentas por cobrar que probablemente no se pagarán.',
    gap: 'No se registra el deterioro de la cartera',
    fix: 'Analice la cartera vencida al cierre y reconozca una pérdida por deterioro cuando haya evidencia de no pago.' },
  { id: 'd3-prestamos', dimension: 'D3', order: 270, weight: 2, requiresFlag: 'financiamiento', groups: ALL, niifSection: 'Sección 11', lesson: 'instrumentos-financieros',
    text: '¿Registra sus préstamos al costo amortizado, incluyendo intereses y costos de la operación?',
    help: 'El costo amortizado reparte intereses y comisiones a lo largo del crédito.',
    gap: 'Los préstamos no se miden al costo amortizado',
    fix: 'Calcule la tasa de interés efectiva de cada préstamo y registre los intereses con ella.' },
  { id: 'd3-ingresos', dimension: 'D3', order: 280, weight: 3, requiresFlag: null, groups: ALL, niifSection: 'Sección 23', lesson: 'ingresos',
    text: '¿Registra los ingresos cuando entrega el bien o presta el servicio, y no cuando cobra?',
    help: 'El momento del cobro no define cuándo hay ingreso.',
    gap: 'Los ingresos no se reconocen cuando se entrega el bien o servicio',
    fix: 'Registre el ingreso al transferir el bien o prestar el servicio, sin importar cuándo se cobre.' },
  { id: 'd3-impuesto-diferido', dimension: 'D3', order: 290, weight: 2, requiresFlag: null, groups: [1, 2], niifSection: 'Sección 29', lesson: 'impuesto-ganancias',
    text: '¿Calcula el impuesto diferido?',
    help: 'Surge de diferencias entre el valor contable y el valor fiscal de activos y pasivos.',
    gap: 'No se calcula el impuesto diferido',
    fix: 'Compare saldos contables y fiscales al cierre y reconozca el impuesto diferido por las diferencias temporarias.' },
  { id: 'd3-beneficios', dimension: 'D3', order: 300, weight: 2, requiresFlag: 'empleados', groups: ALL, niifSection: 'Sección 28', lesson: 'beneficios-empleados',
    text: '¿Registra al cierre las prestaciones sociales y vacaciones que debe a sus empleados?',
    help: 'Cesantías, intereses, prima y vacaciones se registran a medida que se causan.',
    gap: 'Las obligaciones laborales no se registran al cierre',
    fix: 'Consolide y registre al cierre las prestaciones y vacaciones causadas y no pagadas.' },
  { id: 'd3-provisiones', dimension: 'D3', order: 310, weight: 2, requiresFlag: null, groups: ALL, niifSection: 'Sección 21', lesson: 'provisiones',
    text: '¿Registra provisiones por demandas, garantías u otras obligaciones probables?',
    help: 'Si no tiene ninguna, responda Sí.',
    gap: 'No se evalúan provisiones por obligaciones probables',
    fix: 'Revise al cierre los procesos y compromisos, y registre provisiones cuando el pago sea probable y medible.' },

  // D4 · Revelaciones
  { id: 'd4-politicas', dimension: 'D4', order: 410, weight: 2, requiresFlag: null, groups: ALL, niifSection: 'Sección 8', lesson: 'notas',
    text: '¿Las notas describen las políticas contables que aplica?',
    help: 'Por ejemplo, cómo mide inventarios o cuánto dura cada tipo de activo.',
    gap: 'Las notas no describen las políticas contables',
    fix: 'Incluya una nota de políticas contables significativas.' },
  { id: 'd4-juicios', dimension: 'D4', order: 420, weight: 2, requiresFlag: null, groups: ALL, niifSection: 'Sección 8', lesson: 'notas',
    text: '¿Revela los juicios y estimaciones importantes, como vidas útiles, deterioros y provisiones?',
    help: 'Explican las decisiones que más afectan las cifras.',
    gap: 'No se revelan juicios ni estimaciones clave',
    fix: 'Agregue una nota con los juicios y las fuentes de incertidumbre en las estimaciones.' },
  { id: 'd4-hechos', dimension: 'D4', order: 430, weight: 1, requiresFlag: null, groups: ALL, niifSection: 'Sección 32', lesson: 'hechos-posteriores',
    text: '¿Revisa y revela los hechos ocurridos después del cierre que afectan las cifras?',
    help: 'Por ejemplo, la quiebra de un cliente importante en enero.',
    gap: 'No se revisan los hechos posteriores al cierre',
    fix: 'Antes de aprobar los estados, revise hechos posteriores y ajuste o revele según corresponda.' },
  { id: 'd4-partes', dimension: 'D4', order: 440, weight: 2, requiresFlag: null, groups: ALL, niifSection: 'Sección 33', lesson: 'partes-relacionadas',
    text: '¿Revela las operaciones con socios, sus familiares y empresas relacionadas?',
    help: 'Préstamos a socios, compras a empresas de la familia, salarios de la gerencia.',
    gap: 'No se revelan las operaciones con partes relacionadas',
    fix: 'Identifique las partes relacionadas y revele saldos, transacciones y la remuneración de la gerencia.' },

  // D5 · Cierre contable
  { id: 'd5-conciliaciones', dimension: 'D5', order: 510, weight: 3, requiresFlag: null, groups: ALL, niifSection: 'Control interno', lesson: 'cierre-contable',
    text: '¿Concilia bancos, cartera y proveedores cada mes?',
    help: 'Comparar sus registros con extractos y estados de cuenta.',
    gap: 'No se hacen conciliaciones mensuales',
    fix: 'Concilie cada mes bancos, cartera y proveedores y corrija las diferencias.' },
  { id: 'd5-cierre', dimension: 'D5', order: 520, weight: 2, requiresFlag: null, groups: ALL, niifSection: 'Control interno', lesson: 'cierre-contable',
    text: '¿Hace un cierre contable cada mes?',
    help: 'Dejar el mes cuadrado antes de empezar el siguiente.',
    gap: 'No se hace cierre contable mensual',
    fix: 'Defina un calendario de cierre mensual con responsables y fechas.' },
  { id: 'd5-software', dimension: 'D5', order: 530, weight: 1, requiresFlag: null, groups: ALL, niifSection: 'Control interno', lesson: 'cierre-contable',
    text: '¿Lleva la contabilidad en un software contable y no solo en hojas de cálculo?',
    help: 'Reduce errores y deja rastro de cada cambio.',
    gap: 'La contabilidad depende de hojas de cálculo',
    fix: 'Use un software contable con plan de cuentas bajo NIIF.' },
  { id: 'd5-fiscal', dimension: 'D5', order: 540, weight: 2, requiresFlag: null, groups: ALL, niifSection: 'Sección 29', lesson: 'impuesto-ganancias',
    text: '¿Separa la contabilidad NIIF de los ajustes para la declaración de renta?',
    help: 'Las cifras fiscales y las contables pueden ser distintas; se concilian, no se mezclan.',
    gap: 'Las cifras contables se mezclan con criterios fiscales',
    fix: 'Lleve la contabilidad bajo NIIF y prepare aparte la conciliación fiscal.' },
  { id: 'd5-soportes', dimension: 'D5', order: 550, weight: 1, requiresFlag: null, groups: ALL, niifSection: 'Control interno', lesson: 'cierre-contable',
    text: '¿Todos los registros tienen su soporte documental organizado?',
    help: 'Facturas, contratos, extractos y actas.',
    gap: 'Los registros no tienen soportes organizados',
    fix: 'Archive digitalmente el soporte de cada registro.' },
]
